<?xml version="1.0"?>
<package format="3">
  <name>rbvogui_ur_sim_setup</name>
  <version>0.0.0</version>
  <description>Minimal setup notes and vcs manifests for Robotnik RB-VOGUI + UR simulation experiments.</description>
  <maintainer email="rosmatch@todo.todo">rosmatch</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
